### ISSUE TITLE
Break rows are not working on custom edition of messages, headlines and summaries. 

### ISSUE THREAD

**Issue by ExpandedVenture** [ExpandedVenture/ConnectionSphere#10]
![image](https://user-images.githubusercontent.com/87434466/126072484-dacd6ec2-618e-4c3e-96aa-6a75a736d877.png)

![image](https://user-images.githubusercontent.com/87434466/126072491-0268c8dd-21c3-43c6-9618-33f29b87dc9a.png)

**Comment by ExpandedVenture** [comment]
Additonally, add validations for the max-chars limits.

- https://www.mcgill.ca/caps/files/caps/gcs2014_linkedincharacterlimits.pdf

- https://www.linkedin.com/pulse/what-maximum-linkedin-character-your-summary-12-top-2017-caprelli

**Comment by leandrosardi** [comment]
Fixed!
