### ISSUE TITLE
Messages get cancelled after staying pending

### ISSUE THREAD

**Issue by anee786** [ExpandedVenture/ConnectionSphere#216]
Client name: hclark@usbusinessrecovery.com

Lead names: Lars Koerber
Jeff Brungo
Michael Cerce
Brett Hollifield

**Comment by leandrosardi** [comment]
@anee786 

Here is the reply to hclark and any other client who reported the same issue:

> Messages like this one were stuck in que queue, because of a new design of LinkedIn pages.
> 
> Then, the same message were canceled because the lead replied before we could deliver it.
> 
> I new fix patch to resolve the new LinkedIn design will be released within the next 12 hours.

![image](https://user-images.githubusercontent.com/55877846/151967952-6ea71894-c607-4d29-baf3-961482dd9a6a.png)

**Comment by leandrosardi** [comment]
Message to the clients who complained about this issue.

> We have released a fix patch for the new LinkedIn page-design.
> 
> New messages created from now on, should not face this problem.

**Comment by anee786** [comment]
Done
