### ISSUE TITLE
Client is not receiving Leads on linkedin profile

### ISSUE THREAD

**Issue by anee786** [ExpandedVenture/ConnectionSphere#232]
Client name: Eric LeRiche lerichemarketing@gmail.com
![image](https://user-images.githubusercontent.com/76562101/154532546-0bf4901e-7bfe-4ce5-ad2b-0a17a2b34b25.png)

![image](https://user-images.githubusercontent.com/76562101/154534255-5a49097e-4062-41ac-863d-6cfbbfa4accc.png)

**Comment by leandrosardi** [comment]
@anee786 
This issue is a replication of https://github.com/leandrosardi/flywheel/issues/633.

**Comment by leandrosardi** [comment]
@anee786 
I just sent this ticket to the client:

> Hello again Eric,
> 
> > Anee reported this issue about group chats: https://github.com/ExpandedVenture/ConnectionSphere/issues/232
> 
> I am glad to say that this issue has been fixed.
> 
> I just created a transfer from your account, and the group chat between you and the leads has been created.
> 
> Please check out the 2 screenshots below.
> 
> >  I transferred another one yesterday and there is no sign of it and all th e other are not in my system either
> 
> There are 12 transfers created by you that are still stuck before they have been created before this fix patch release.
> 
> Please let me know if you want I reset them and get them delivered.
> 
> The leads are:
> Al Lucas
> Spiro Frangos
> John Paul Robinson
> Spiro Frangos
> Al Lucas
> Tony Kutch
> Alison Cowan
> Nancy "Nayana" Patel CHIA, CHO
> Don Kajans
> brian begos
> Kunal Mody
> Roosevelt R. Blake
> 
> >  I need to get this fixed asap because I want to upgrade to the Hulk level and send the leads to 4 different people so it needs to be working flawlessly
> 
> If you are still willing to upgrade, please use the link below:
> https://euler.connectionsphere.com/settings/filter_goto_invoice_paypal?iid=96F9709A-81C1-4661-B820-E42D6D668293
> 
> >  I always used Send and transfer because obviously I need to answer them
> 
> That is fine.

**Comment by leandrosardi** [comment]
I am closing this issue.
