### ISSUE TITLE
Enable/Disable create group chat on introduction messages

### ISSUE THREAD

**Issue by ExpandedVenture** [ExpandedVenture/ConnectionSphere#49]
# Guidelines:

1. client and pipeline-level (done)
2. class methods (done)
3. ask for pipeline.gct_on_introduction_message when editing a pipeline (done)
4. ask for client.gct_on_introduction_message in the pipelines screen (done)
5. ask for client.gct_on_introduction_message when finishing the wizard
6. ask for client.gct_on_introduction_message when connecting the LinkedIn accounts in the pipelines screen
7. decide message.gct when creating a new message
8. decide message.gct when creating a new pipeline
9. documentacion in the help center
10. should we send a notification of introduction messages only if the gct-on-intros is active for the message ? --> No. Develop a communication setup in other screen (#50)

**Comment by leandrosardi** [comment]
![image](https://user-images.githubusercontent.com/55877846/129893416-7a7548df-c46f-4744-bbf3-4c545e8463c2.png)
![image](https://user-images.githubusercontent.com/55877846/129893448-cd45175d-d460-4c9a-a7cf-4c3290d21756.png)
