### ISSUE TITLE
Latest jobs are being completed with long delay

### ISSUE THREAD

**Issue by ExpandedVenture** [ExpandedVenture/ConnectionSphere#8]
![image](https://user-images.githubusercontent.com/87434466/125821382-347e0e75-def2-4415-a185-64ca9ad63e29.png)

**Comment by ExpandedVenture** [comment]
After complete 88% of a job, it got stuck or moving forward very slow:

![image](https://user-images.githubusercontent.com/87434466/128849640-c230e614-ffee-4b09-ab6f-0c0c19909466.png)

**Comment by ExpandedVenture** [comment]
The jobs resumed theirselves. No any patch has been released.

The problem is the daily login quota assigned to the accounts.
That is causing some accounts keep on hold, waiting for the next day to resume their jobs.

Extending the daily quota of new accounts is risky.
The only way is to assign more accounts for free, as a bonus.

A nice solution to don't get the user panicking is to add a label to each job, informing the number of these XX pending jobs that are allowed to run right now. Need designing mockup for this proposal.

![image](https://user-images.githubusercontent.com/87434466/128938093-6e591297-6dfd-498f-966e-17cf3e0ff4b7.png)

**Comment by ExpandedVenture** [comment]
The latest jobs are moving slow because they are all assigned to the same worker thread.

Develop a dispatching process using [Pampa](https://github.com/leandrosardi/pampa).

![image](https://user-images.githubusercontent.com/87434466/129011688-67c0157d-938f-4c56-b6f5-80404a57f278.png)

**Comment by ExpandedVenture** [comment]
This issue is related with #39.

**Comment by ExpandedVenture** [comment]
## Technical Outline

+ develop the Command::get_next method
+ dispatcher
	+ good coordination of the run_tries between notify_run_start.json and get_command.json
	+ selecting function, to use the same query than get_command.json
	+ relauncher function, to relaunch commands too when relaunching job
+ notify_run_start.json --> update job.run_start_time and job.run_tries if it is the command #1
+ notify_run_finish.json --> update job.run_end_time if all commands have finished with run_status=1
+ get_command.json --> filter jobs with job.run_tries < 3
+ get_progress.json --> move queries to Run class methods
+ screen show as failed jobs only when job.run_tries >= 3
+ dedicated dispatcher for CrowdTrust: /p/dispatcher.crowdtrust.rb
+ show "on hold" label

**Comment by ExpandedVenture** [comment]
Done.

**Comment by leandrosardi** [comment]
I added the "on hold" flag to jobs that cannot be processed right now because the accounts assigned have reached either their hourly or daily quota.

![image](https://user-images.githubusercontent.com/55877846/129634076-512e31ed-9da9-4795-9bc2-5647902c59ef.png)
